### ISSUE TITLE
Unexpected token `...`

### ISSUE THREAD

**Issue by Mansour-J** [react-monaco-editor/react-monaco-editor#125]
I get the following error when I run the example,  (I made sure that I added webpack monaco editor plugin)

```
λ yarn start
yarn run v1.5.1
$ webpack-dev-server --hot --inline --progress --colors --port 8886
/Users/Mansour/Desktop/test/react-monaco-editor/react-monaco-editor/example/node_modules/monaco-editor-webpack-plugin/index.js:40
    [id, ...(language.alias || [])].map((label) => [label, { label, ...language }])
                                                                    ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Mansour/Desktop/test/react-monaco-editor/react-monaco-editor/example/webpack.config.js:1:91)
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c webpack-dev-server --hot --inline --progress --colors --port 8886
Directory: /Users/Mansour/Desktop/test/react-monaco-editor/react-monaco-editor/example
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/Mansour/Desktop/test/react-monaco-editor/react-monaco-editor/example/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

For my environment and version of `node`, `npm`, `yarn`, ....  please visit the yarn-error log

[yarn-error.log](https://github.com/superRaytin/react-monaco-editor/files/2016100/yarn-error.log)

**Comment by domoritz** [comment]
Try a newer version of node that supports es6.
