### ISSUE TITLE
yarn start failed with error Command failed with exit code 1

### ISSUE THREAD

**Issue by foreversue** [react-monaco-editor/react-monaco-editor#168]
$ yarn start
yarn run v1.12.3
$ webpack-dev-server --hot --inline --progress --colors --port 8886
C:\Users\su\react-monaco-editor\example\node_modules\webpack-dev-server\bin\webpack-dev-server.js:343
    throw err;
    ^

Error: Cannot find module 'monaco-editor\esm\vs\editor\standalone\browser\accessibilityHelp\accessibilityHelp'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at resolveMonacoPath (C:\Users\su\react-monaco-editor\example\node_modules\monaco-editor-webpack-plugin\index.js:
21:18)
    at use.options.pre.featurePaths.map (C:\Users\su\react-monaco-editor\example\node_modules\monaco-editor-webpack-p
lugin\index.js:133:51)
    at Array.map (<anonymous>)
    at createLoaderRules (C:\Users\su\react-monaco-editor\example\node_modules\monaco-editor-webpack-plugin\index.js:
133:31)
    at MonacoWebpackPlugin.apply (C:\Users\su\react-monaco-editor\example\node_modules\monaco-editor-webpack-plugin\i
ndex.js:71:19)
    at webpack (C:\Users\su\react-monaco-editor\example\node_modules\webpack\lib\webpack.js:47:13)
    at startDevServer (C:\Users\su\react-monaco-editor\example\node_modules\webpack-dev-server\bin\webpack-dev-server
.js:335:16)
    at processOptions (C:\Users\su\react-monaco-editor\example\node_modules\webpack-dev-server\bin\webpack-dev-server
.js:309:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by domoritz** [comment]
Did you run yarn install?

**Comment by masuidrive** [comment]
You should run "yarn" on root dir first.
I got same error now :-)

**Comment by masuidrive** [comment]
```
git clone https://github.com/superRaytin/react-monaco-editor.git
cd react-monaco-editor
yarn ← probably you forgot it
cd example
yarn
yarn start
```

**Comment by arxenix** [comment]
@domoritz could you explain why you need to run yarn install on the root dir to be able to run these examples? Why isn't just the yarn install inside the example dir sufficient?

**Comment by domoritz** [comment]
The example relies on the package that is compiled at the top level rather than the released version.
