### ISSUE TITLE
Not working with nextjs?

### ISSUE THREAD

**Issue by vallerion** [react-monaco-editor/react-monaco-editor#271]
**Describe the bug**
i try to use react-monaco-editor with next.js based [on this tutorial](https://github.com/resourcesco/snippets/blob/master/docs/monaco-editor-with-next.md). But all time i have a lot of errors:
```
Uncaught (in promise) Error: Unexpected usage
    at EditorSimpleWorker.push../node_modules/monaco-editor/esm/vs/editor/common/services/editorSimpleWorker.js.EditorSimpleWorker.loadForeignModule (editorSimpleWorker.js:540)
    at webWorker.js:54
```
```
Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at push../node_modules/normalize-url/index.js.module.exports (index.js:46)
    at getReloadUrl (hotModuleReplacement.js:74)
    at hotModuleReplacement.js:92
    at NodeList.forEach (<anonymous>)
    at reloadStyle (hotModuleReplacement.js:89)
    at update (hotModuleReplacement.js:119)
    at invokeFunc (debounce.js:95)
    at trailingEdge (debounce.js:144)
    at timerExpired (debounce.js:132)
```
```
Uncaught (in promise) Error: Unexpected usage
    at EditorSimpleWorker.push../node_modules/monaco-editor/esm/vs/editor/common/services/editorSimpleWorker.js.EditorSimpleWorker.loadForeignModule (editorSimpleWorker.js:540)
    at webWorker.js:54
```

my code:
```jsx
import React from 'react'
import PropTypes from 'prop-types'
import * as monaco from '@timkendrick/monaco-editor/dist/external'
import MonacoEditor from 'react-monaco-editor'
window.MonacoEnvironment = { baseUrl: '/monaco-editor-external' }

/**
 * @param {string} code
 * @returns {*}
 * @constructor
 */
const CodeEditor = ({code}) => {
    const options = {
        selectOnLineNumbers: true
    }

    return (
        <MonacoEditor
            // width="800"
            height="600"
            language="javascript"
            theme="vs"
            // theme="vs-dark"
            value={''}
            options={options}
            onChange={() => {}}
            editorDidMount={() => {}}
        />
    )
}

CodeEditor.propTypes = {
    code: PropTypes.string.isRequired,
}

export default CodeEditor
```

in server.js added:
```js
...
    server.use(
        '/monaco-editor-external',
        express.static(`${__dirname}/node_modules/@timkendrick/monaco-editor/dist/external`)
    )
...
```

**To Reproduce**
install
"react-monaco-editor": "^0.34.0"
"monaco-editor": "^0.20.0"
"monaco-editor-webpack-plugin": "^1.9.0"
"@timkendrick/monaco-editor": "0.0.9"
"next": "^9.2.1"
"react": "^16.12.0"

**Expected behavior**
work without errors

**Environment (please complete the following information):**
 - OS: mac
 - Browser chrome
 - Bundler webpack

guys, please, help me. I spent for that a lot of time, i tried use with/without `MonacoWebpackPlugin`, with/without [@stoplight/monaco](https://www.npmjs.com/package/@stoplight/monaco), but i still got error :(

**Comment by Ehesp** [comment]
Trying to get this working myself, has been rather painful so far, lots of Googling & reading....

So far I have it working with `javascript` syntax, but using say `typescript` throws errors about the service workers not working. Putting this here to document where I have got to for others:

First off, you need to install the CSS & font loader plugins for NextJS:

`yarn add @zeit/next-css next-fonts`

This allows the css which monaco imports internally to be parsed, and also the fonts they bundle/load to be parsed:

```js
// next.config.js
const withCSS = require("@zeit/next-css");
const withFonts = require("next-fonts");

module.exports = withCSS(withFonts({}));
```

Next up, I added the webpack plugin. If I leave the languages out it complains (even though the docs suggest it defaults to them all?):

```js
// next.config.js
const withCSS = require('@zeit/next-css');
const withFonts = require('next-fonts');
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');

module.exports = withCSS(withFonts({
  config.plugins.push(new MonacoWebpackPlugin({
    languages: ['javascript']
  }));
}));
```

Then I had some errors about the service works not being found... so I added the `worker-loader`:

`yarn add worker-loader`

I added the rules to parse any of the "[language].worker.js" files:

```js
// next.config.js
const withCSS = require('@zeit/next-css');
const withFonts = require('next-fonts');
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');

module.exports = withCSS(withFonts({
  config.plugins.push(new MonacoWebpackPlugin({
    languages: ['javascript']
  }));

  config.module.rules.push({
    test: /\.worker\.js$/,
    use: {
      loader: 'worker-loader',
        options: { inline: true }
      }
   });

   return config;
}));
```

Now back in my pages file, I import the module. It doesn't seem to be compatible with SSR, so I just load it on the client (don't think this is a big issue anyway, who wants code to be indexed?):

```js
// pages/index.js

import React, { useEffect } from "react";
import dynamic from "next/dynamic";

const MonacoEditor = dynamic(import("react-monaco-editor"), { ssr: false });

function IndexPage() {
  return (
    <MonacoEditor
      width="800"
      height="600"
      language="javascript"
      theme="vs-dark"
      value={`const foo = 'bar';`}
      options={{
        selectOnLineNumbers: true
      }}
      onChange={console.log}
    />
  );
}

export default IndexPage;
```

So this currently works, with the worker seemingly doing it's job highlighting in the background. If the worker isn't loaded, there is a lot of lag when typing:

![image](https://user-images.githubusercontent.com/842078/77187293-241d6400-6acc-11ea-9dd0-6f751c3e6ee7.png)

**Comment by Ehesp** [comment]
Ok, I don't think it's properly working with `javascript`. It seems monaco uses service workers to do most of the heavy lifting, however if you look in the console network tab, there is a few `editor.worker.js`/`ts.worker.js` 404 errors.

The `MonacoWebpackPlugin` then say that the `javascript` parser requires that the `typescript` language is added as they share the same worker... If I add `typescript` I get a load of console errors, guessing it's because it's now actually trying to find the `ts.worker.js` file but it doesn't exist? With just `javascript`, there is no worker so seems to not try to load a worker file (not really sure).

I'll keep digging.

**Comment by Ehesp** [comment]
Ok, so if you add languages (in this case `typescript`) to the `MonacoWebpackPlugin`, it does actually create a JavaScript file in the `.next` build:

![image](https://user-images.githubusercontent.com/842078/77188085-5a0f1800-6acd-11ea-890f-ed3d989b448a.png)


The network tab shows it trying to load this file, but it can't access it:

![image](https://user-images.githubusercontent.com/842078/77188121-6d21e800-6acd-11ea-9602-4ab42afce735.png)


I guess it needs to be exported as a static in Next...?

**Comment by Ehesp** [comment]
Figured out how to override the worker URL that monaco uses to load the workers:

```jsx
<MonacoEditor
  editorDidMount={() => {
    window.MonacoEnvironment.getWorkerUrl = (_moduleId: string, label: string) => {
      if (label === 'json') return 'static/monaco/json.worker.js';
      if (label === 'css') return 'static/monaco/css.worker.js';
      if (label === 'html') return 'static/monaco/html.worker.js';
      if (label === 'typescript' || label === 'javascript')
        return 'static/monaco/ts.worker.js';
      return 'static/monaco/editor.worker.js';
     };
}}
```

Now I just need to figure out how to get them loaded from the Next build...

**Comment by Ehesp** [comment]
Ok figured it out 😄

`next.js.config`:

```js
const withCSS = require("@zeit/next-css");
const withFonts = require("next-fonts");
const MonacoWebpackPlugin = require("monaco-editor-webpack-plugin");

module.exports = withCSS(
  withFonts({
    webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
      config.plugins.push(
        new MonacoWebpackPlugin({
          languages: ["javascript", "typescript"],
          filename: "static/[name].worker.js"
        })
      );

      return config;
    }
  })
);
```

Now, in the `index.js` page file:

```js
import React from "react";
import dynamic from "next/dynamic";

const MonacoEditor = dynamic(import("react-monaco-editor"), { ssr: false });

function IndexPage() {
  return (
    <MonacoEditor
      editorDidMount={() => {
        window.MonacoEnvironment.getWorkerUrl = (
          _moduleId: string,
          label: string
        ) => {
          if (label === "json") return "_next/static/json.worker.js";
          if (label === "css") return "_next/static/css.worker.js";
          if (label === "html") return "_next/static/html.worker.js";
          if (label === "typescript" || label === "javascript")
            return "_next/static/ts.worker.js";
          return "_next/static/editor.worker.js";
        };
      }}
    />
  );
}

export default IndexPage;
```

If you read all the way down, turns out `worker-loader` did nothing, so you can remove that. 

They key is to set the `MonacoWebpackPlugin` `filename` key to have the `static` prefix, so it's added to the `.next/static` build output, which is then exposed via a HTTP request under `_next/static/`. 

Happy coding!

**Comment by Ehesp** [comment]
https://github.com/zeit/next.js/pull/11232

**Comment by sw-yx** [comment]
nice work @Ehesp !

**Comment by Ehesp** [comment]
If you check the console while you type it will probably spit out a load of errors, which are related to the service worker not running

By default Monaco just tries to load the works from a base url like site.com/ts.worker.js

That doesn't exist with next js, so you have to provide Monaco with the paths which next exposes them as

**Comment by danielpaz6** [comment]
@Ehsep does it work for you?

I mean, I tried to install your pull: 
https://github.com/zeit/next.js/tree/canary/examples/with-monaco-editor

but it doesn't work and make this error:

```
[ ready ] compiled successfully - ready on http://localhost:3000
[ event ] build page: /
[ wait ]  compiling ...
[ error ] ./node_modules/monaco-editor/esm/vs/base/browser/ui/codiconLabel/codicon/codicon.css
ModuleParseError: Module parse failed: Unexpected character ' ' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
Could not find files for /index in .next/build-manifest.json
ModuleBuildError: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleParseError: Module parse failed: Unexpected character ' ' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
    at handleParseError (D:\monaco-editor\node_modules\webpack\lib\NormalModule.js:469:19)
    at D:\monaco-editor\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\monaco-editor\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\monaco-editor\node_modules\loader-runner\lib\LoaderRunner.js:373:3       
    at iterateNormalLoaders (D:\monaco-editor\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (D:\monaco-editor\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (D:\monaco-editor\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at D:\monaco-editor\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at D:\monaco-editor\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
    at D:\monaco-editor\node_modules\webpack\lib\NormalModule.js:316:20
    at D:\monaco-editor\node_modules\loader-runner\lib\LoaderRunner.js:367:11      
    at D:\monaco-editor\node_modules\loader-runner\lib\LoaderRunner.js:182:20      
    at context.callback (D:\monaco-editor\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\monaco-editor\node_modules\mini-css-extract-plugin\dist\loader.js:112:14 
    at D:\monaco-editor\node_modules\webpack\lib\Compiler.js:343:11
    at D:\monaco-editor\node_modules\webpack\lib\Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\monaco-editor\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:22:1)
    at AsyncSeriesHook.lazyCompileHook (D:\monaco-editor\node_modules\tapable\lib\Hook.js:154:20)
    at D:\monaco-editor\node_modules\webpack\lib\Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\monaco-editor\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (D:\monaco-editor\node_modules\tapable\lib\Hook.js:154:20)
    at D:\monaco-editor\node_modules\webpack\lib\Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\monaco-editor\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (D:\monaco-editor\node_modules\tapable\lib\Hook.js:154:20)
    at D:\monaco-editor\node_modules\webpack\lib\Compilation.js:1414:32
ModuleBuildError: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleParseError: Module parse failed: Unexpected character ' ' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
    at handleParseError (D:\monaco-editor\node_modules\webpack\lib\NormalModule.js:469:19)
    at D:\monaco-editor\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\monaco-editor\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\monaco-editor\node_modules\loader-runner\lib\LoaderRunner.js:373:3       
    at iterateNormalLoaders (D:\monaco-editor\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (D:\monaco-editor\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (D:\monaco-editor\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at D:\monaco-editor\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at D:\monaco-editor\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
    at D:\monaco-editor\node_modules\webpack\lib\NormalModule.js:316:20
    at D:\monaco-editor\node_modules\loader-runner\lib\LoaderRunner.js:367:11      
    at D:\monaco-editor\node_modules\loader-runner\lib\LoaderRunner.js:182:20      
    at context.callback (D:\monaco-editor\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\monaco-editor\node_modules\mini-css-extract-plugin\dist\loader.js:112:14 
    at D:\monaco-editor\node_modules\webpack\lib\Compiler.js:343:11
    at D:\monaco-editor\node_modules\webpack\lib\Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\monaco-editor\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:22:1)
    at AsyncSeriesHook.lazyCompileHook (D:\monaco-editor\node_modules\tapable\lib\Hook.js:154:20)
    at D:\monaco-editor\node_modules\webpack\lib\Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\monaco-editor\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (D:\monaco-editor\node_modules\tapable\lib\Hook.js:154:20)
    at D:\monaco-editor\node_modules\webpack\lib\Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\monaco-editor\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (D:\monaco-editor\node_modules\tapable\lib\Hook.js:154:20)
    at D:\monaco-editor\node_modules\webpack\lib\Compilation.js:1414:32
```

**Comment by Ehesp** [comment]
Yeah it works for me. What is in the CSS file it's failing at? Generally the CSS & Font loader sorted that out.

**Comment by danielpaz6** [comment]
That's the CSS File: https://pastebin.com/zgjLK6S6

I also opened an issue on nextjs so we could concentrate everything there: https://github.com/zeit/next.js/issues/13117

I noticed that if you use the versions in the in package.json without the `^` ( without upgrade it ) it does work ( more info on the issue I opened )

Hopefully you could spot the bug!

**Comment by sombreroEnPuntas** [comment]
I'm using next.js also :atom: 

Followed the instructions [here](https://github.com/react-monaco-editor/react-monaco-editor/issues/271#issuecomment-601835902) but still not working.

Two issues for me:
1. Seems like the service workers are not pickedup by next... how did you manage to make them part of the static folder on nextjs?

2. I get the editor rendered, but on `editorDidMount` I get the following:
```
Uncaught TypeError: Cannot set property 'getWorkerUrl' of undefined
```
`MonacoEnvironment` is not present on global scope. Is something maybe not getting loaded by webpack plugin?
Made a poly-fill with just an empty object, and the editor loads. but since there are no workers no language highlight happens :)

**Comment by subwaymatch** [comment]
I've spent a few days trying to make `react-monaco-editor` with next.js. It just didn't work :weary:. While next.js has [an example with `react-monaco-editor` ](https://github.com/vercel/next.js/tree/canary/examples/with-monaco-editor)in the official repo, it doesn't seem to work out-of-the-box with Tailwind or sass. Even if I do get it to work, I don't like the idea of polluting the Webpack config (and having to install extra packages).

A much, much better alternative IMHO is to use [@monaco-editor/react](https://github.com/suren-atoyan/monaco-react). I'm using css modules with sass, and it works like magic (especially after spending a few days with this package). I also didn't have to fiddle with `next.config.js`. For those who may be interested, there's a [CodeSandbox example](https://codesandbox.io/s/monaco-react-issue-101-u1g1w?file=/pages/index.tsx) with Next.js.

**Screenshot of how I'm using it**
![image](https://user-images.githubusercontent.com/1064036/90054777-eb13a500-dca1-11ea-8f0b-f4d0063d4c4d.png)

**Comment by benebsiny** [comment]
I've followed @Ehesp to change the `next.config.js` and `index.js`, and now it shows the error message...
```
./node_modules/monaco-editor/esm/vs/base/browser/ui/codiconLabel/codicon/codicon.css
ModuleParseError: Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
```
Any solution ?😭

**Comment by sunderls** [comment]
@subwaymatch thx, you saved my day!

[@monaco-editor/react](https://www.npmjs.com/package/@monaco-editor/react) just works out of the box, no need to mess up with next.js config

**Comment by softmarshmallow** [comment]
> @subwaymatch thx, you saved my day!
> 
> [@monaco-editor/react](https://www.npmjs.com/package/@monaco-editor/react) just works out of the box, no need to mess up with next.js config

Not working for me.

**Comment by subwaymatch** [comment]
> > @subwaymatch thx, you saved my day!
> > [@monaco-editor/react](https://www.npmjs.com/package/@monaco-editor/react) just works out of the box, no need to mess up with next.js config
> 
> Not working for me.

Have you tried using `next/dynamic` with the `{ ssr: false }` option to dynamically import the module? From what I recall, I had to disable SSR for the component using @monaco-editor/react.

```tsx
// components/CodeEditor.tsx
import Editor from "@monaco-editor/react";

const CodeEditor = () => (
    <Editor />
);

export default CodeEditor;
```

```tsx
// pages/index.tsx
import dynamic from "next/dynamic";

const CodeEditor = dynamic(() => import("components/CodeEditor"), {
  ssr: false,
});

export default function TestPage() {
  return (
    <>
        <h1>Code Editor with Dynamic Import</h1>
        <CodeEditor  />
    </>
  );
}
```

**Comment by softmarshmallow** [comment]
> @subwaymatch thx, you saved my day!
> 
> [@monaco-editor/react](https://www.npmjs.com/package/@monaco-editor/react) just works out of the box, no need to mess up with next.js config

Have you experienced `Module not found: Can't resolve '@monaco-editor/react'` error while using `@monaco-editor/react` with nextjs?

**Comment by anubra266** [comment]
> > @subwaymatch thx, you saved my day!
> > [@monaco-editor/react](https://www.npmjs.com/package/@monaco-editor/react) just works out of the box, no need to mess up with next.js config
> 
> Have you experienced `Module not found: Can't resolve '@monaco-editor/react'` error while using `@monaco-editor/react` with nextjs?

It means you've not installed it.

**Comment by softmarshmallow** [comment]
> > > @subwaymatch thx, you saved my day!
> > > [@monaco-editor/react](https://www.npmjs.com/package/@monaco-editor/react) just works out of the box, no need to mess up with next.js config
> > 
> > 
> > Have you experienced `Module not found: Can't resolve '@monaco-editor/react'` error while using `@monaco-editor/react` with nextjs?
> 
> It means you've not installed it.

Of course, i'm aware of that. turns out i've installed `@monaco-editor/react` but did not installed `monaco-editor` and the error throws irrelevant `Module not found: Can't resolve '@monaco-editor/react'`. Thanks for the reply anyway! good day

**Comment by Lunaticsatoshi** [comment]
> I've spent a few days trying to make `react-monaco-editor` with next.js. It just didn't work 😩. While next.js has [an example with `react-monaco-editor` ](https://github.com/vercel/next.js/tree/canary/examples/with-monaco-editor) in the official repo, it breaks as soon as I add Tailwind or sass. Even if I do get it to work with the [tutorial here](https://dev.to/swyx/how-to-add-monaco-editor-to-a-next-js-app-ha3), I don't like the idea of polluting the Webpack config (and having to install extra packages).
> 
> A much, much better alternative IMHO is to use [@monaco-editor/react](https://github.com/suren-atoyan/monaco-react). I'm using css modules with sass, and it works like magic (especially after spending a few days with this package). I also didn't have to fiddle with `next.config.js`. For those who may be interested, there's a simplified [CodeSandbox example](https://codesandbox.io/s/monaco-react-issue-101-u1g1w?file=/pages/index.tsx) with Next.js by the author of that package.
> 
> **Screenshot of how I'm using it**
> ![image](https://user-images.githubusercontent.com/1064036/90054777-eb13a500-dca1-11ea-8f0b-f4d0063d4c4d.png)

What are you using to compile the code ? :3

**Comment by subwaymatch** [comment]
I used [pyodide](https://github.com/pyodide/pyodide) to run Python code with WebAssembly. 🤖

**Comment by subwaymatch** [comment]
> > I've spent a few days trying to make `react-monaco-editor` with next.js. It just didn't work 😩. While next.js has [an example with `react-monaco-editor` ](https://github.com/vercel/next.js/tree/canary/examples/with-monaco-editor) in the official repo, it breaks as soon as I add Tailwind or sass. Even if I do get it to work with the [tutorial here](https://dev.to/swyx/how-to-add-monaco-editor-to-a-next-js-app-ha3), I don't like the idea of polluting the Webpack config (and having to install extra packages).
> > A much, much better alternative IMHO is to use [@monaco-editor/react](https://github.com/suren-atoyan/monaco-react). I'm using css modules with sass, and it works like magic (especially after spending a few days with this package). I also didn't have to fiddle with `next.config.js`. For those who may be interested, there's a simplified [CodeSandbox example](https://codesandbox.io/s/monaco-react-issue-101-u1g1w?file=/pages/index.tsx) with Next.js by the author of that package.
> > **Screenshot of how I'm using it**
> > ![image](https://user-images.githubusercontent.com/1064036/90054777-eb13a500-dca1-11ea-8f0b-f4d0063d4c4d.png)
> 
> What are you using to compile the code ? :3

I used [pyodide](https://github.com/pyodide/pyodide) to run Python code with WebAssembly. 🤖

**Comment by AlbinoGeek** [comment]
> > > @subwaymatch thx, you saved my day!
> > > [@monaco-editor/react](https://www.npmjs.com/package/@monaco-editor/react) just works out of the box, no need to mess up with next.js config
> > 
> > 
> > Not working for me.
> 
> Have you tried using `next/dynamic` with the `{ ssr: false }` option to dynamically import the component? From what I recall, I had to disable SSR when importing the component using @monaco-editor/react.
> 
> ```tsx
> // components/CodeEditor.tsx
> import Editor from "@monaco-editor/react";
> 
> const CodeEditor = () => (
>     <Editor />
> );
> 
> export default CodeEditor;
> ```
> 
> ```tsx
> // pages/index.tsx
> import dynamic from "next/dynamic";
> 
> const CodeEditor = dynamic(() => import("components/CodeEditor"), {
>   ssr: false,
> });
> 
> export default function TestPage() {
>   return (
>     <>
>         <h1>Code Editor with Dynamic Import</h1>
>         <CodeEditor  />
>     </>
>   );
> }
> ```

```
error - ./node_modules/monaco-editor/esm/vs/base/browser/ui/actionbar/actionbar.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/monaco-editor/esm/vs/base/browser/ui/actionbar/actionViewItems.js
```

Sadly this appears to happen again.

**Comment by medihack** [comment]
After some experiments, I got it working with the help of [next-transpile-modules](https://www.npmjs.com/package/next-transpile-modules).

```js
// next.config.js (in my case blitz.config.ts as I use Blitz.js, but it shouldn't matter)
const nextTranspileModules = require("next-transpile-modules")
...
const withTM = nextTranspileModules(["monaco-editor"])
...
module exports = withTM({
  webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
    config.plugins.push(
        new MonacoWebpackPlugin({
          languages: ["json"],
          features: [],
          filename: "static/[name].worker.js",
        })
      )
  }
})
```

Also, make sure to import the editor dynamically and disable SSR:

```js
import { dynamic } from "blitz"

const MonacoEditor = dynamic(() => import("react-monaco-editor"), { ssr: false })

export const ModuleEditor = () => {
  return (
    <div>
      <MonacoEditor height={300} language="json" />
    </div>
  )
}
```

Also, make sure you only have `react-monaco-editor` and not(!) `monaco-editor` in your dependencies (not sure, but otherwise, it didn't work for me).

I hope this helps someone.

**Comment by AgarwalPragy** [comment]
> Also, make sure you only have react-monaco-editor and not(!) monaco-editor in your dependencies (not sure, but otherwise, it didn't work for me).

without `monaco-editor`, it is unable to resolve the dependencies

>  error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
Error: next-transpile-modules - an unexpected error happened when trying to resolve "monaco-editor". Are you sure the name of the module you are trying to transpile is correct, and it has a package.json with a "main" or an "exports" field?


After adding it, it gives the error

```
error - ./node_modules/monaco-editor/esm/vs/editor/contrib/smartSelect/bracketSelections.js
Module parse failed: The keyword 'yield' is reserved (83:36)
File was processed with these loaders:
 * ./node_modules/@next/react-refresh-utils/loader.js
 * ./node_modules/next/dist/build/webpack/loaders/next-swc-loader.js
You may need an additional loader to handle the result of these loaders.
|                                     result.push(bucket);
|                                     var ranges = new Map();
>                                     yield new Promise(function(resolve) {
|                                         return BracketSelectionRangeProvider._bracketsRightYield(resolve, 0, model, position, ranges);
|                                     });
Could not find files for / in .next/build-manifest.json
Could not find files for / in .next/build-manifest.json
```

What am I missing?

**Comment by AlbinoGeek** [comment]
**The following is what worked for me.**

- NO NEXT CONFIG REQUIRED
- NO TRANSPILE MODULES

## package.json
```
// ...
  "dependencies": {
    "@monaco-editor/react": "^4.2.2",
// ... NO OTHER MONACO IMPORTS
```

## some typescript file
```tsx
import Editor from '@monaco-editor/react'
import {
  Dispatch,
  MutableRefObject,
  SetStateAction,
  useEffect,
  useRef
} from 'react'

//
// So... typings weren't working when I implemented Monaco, and we had to ship,
// so these placeholder types were put in place so tests passed... please fix
// these before going production. imo Monaco provides typings, they just didn't
// work when we tried them (VSCode wouldn't recognize them, tslint complained.)
//

export type MonacoEditorOptions = {
  stopRenderingLineAfter: number
}

export type MonacoEditorA = MutableRefObject<any>
export type MonacoEditorB = MutableRefObject<any>
export type MonacoTextModal = any

export type MonacoOnInitializePane = (
  monacoEditorRef: MonacoEditorA,
  editorRef: MonacoEditorB,
  model: MonacoTextModal
) => void

export type ScriptEditorProps = {
  // usage: const [code, setCode] = useState<string>('default value')
  code: string
  setCode: Dispatch<SetStateAction<string>>

  // see: https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html
  editorOptions: MonacoEditorOptions

  onInitializePane: MonacoOnInitializePane
}

//
// End of placeholder typings
//

const ScriptEditor = (props: ScriptEditorProps): JSX.Element => {
  const { code, setCode, editorOptions, onInitializePane } = props

  const monacoEditorRef = useRef<any | null>(null)
  const editorRef = useRef<any | null>(null)

  // monaco takes years to mount, so this may fire repeatedly without refs set
  useEffect(() => {
    if (monacoEditorRef?.current) {
      // again, monaco takes years to mount and load, so this may load as null
      const model: any = monacoEditorRef.current.getModels()

      if (model?.length > 0) {
        // finally, do editor's document initialization here
        onInitializePane(monacoEditorRef, editorRef, model)
      }
    }
  })

  return <Editor
    height="42.9em" // preference
    language="go"   // preference
    onChange={(value, _event) => {
      setCode(value)
    }}
    onMount={(editor, monaco) => {
      monacoEditorRef.current = monaco.editor
      editorRef.current = editor
    }}
    options={editorOptions}
    theme="vs-dark" // preference
    value={code}
    width="60em"    // preference
  />
}

export default ScriptEditor
```

## example usage
```tsx
import ScriptEditor, { MonacoOnInitializePane } from '../components/ScriptEditor'
import { useState } from 'react'

const Index = () => {
  const [code, setCode] = useState<string>(`
  // Hello, World!
  const foo = 1 + 1
`)

  const onInitializePane: MonacoOnInitializePane = (
    monacoEditorRef,
    editorRef,
    model
  ) => {
    editorRef.current.setScrollTop(1)
    editorRef.current.setPosition({
      lineNumber: 2,
      column: 0,
    })
    editorRef.current.focus()
    monacoEditorRef.current.setModelMarkers(model[0], 'owner', null)
  }

  return <ScriptEditor
    code={code}
    setCode={setCode}
    editorOptions={{
      stopRenderingLineAfter: 1000,
    }}
    onInitializePane={onInitializePane}
  />
}
```

**Comment by ellis** [comment]
@AlbinoGeek Thank you soo much for the simple working example!

**Comment by ed-curran** [comment]
> Ok figured it out smile
> 
> `next.js.config`:
> 
> ```js
> const withCSS = require("@zeit/next-css");
> const withFonts = require("next-fonts");
> const MonacoWebpackPlugin = require("monaco-editor-webpack-plugin");
> 
> module.exports = withCSS(
>   withFonts({
>     webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
>       config.plugins.push(
>         new MonacoWebpackPlugin({
>           languages: ["javascript", "typescript"],
>           filename: "static/[name].worker.js"
>         })
>       );
> 
>       return config;
>     }
>   })
> );
> ```
> 
> Now, in the `index.js` page file:
> 
> ```js
> import React from "react";
> import dynamic from "next/dynamic";
> 
> const MonacoEditor = dynamic(import("react-monaco-editor"), { ssr: false });
> 
> function IndexPage() {
>   return (
>     <MonacoEditor
>       editorDidMount={() => {
>         window.MonacoEnvironment.getWorkerUrl = (
>           _moduleId: string,
>           label: string
>         ) => {
>           if (label === "json") return "_next/static/json.worker.js";
>           if (label === "css") return "_next/static/css.worker.js";
>           if (label === "html") return "_next/static/html.worker.js";
>           if (label === "typescript" || label === "javascript")
>             return "_next/static/ts.worker.js";
>           return "_next/static/editor.worker.js";
>         };
>       }}
>     />
>   );
> }
> 
> export default IndexPage;
> ```
> 
> If you read all the way down, turns out `worker-loader` did nothing, so you can remove that.
> 
> They key is to set the `MonacoWebpackPlugin` `filename` key to have the `static` prefix, so it's added to the `.next/static` build output, which is then exposed via a HTTP request under `_next/static/`.
> 
> Happy coding!

I had to use `/_next/static/<LABEL>.worker.js` (with `<LABEL>` as `json` etc) because my page wasn't at the root. Didn't seem to need to transpile, didn't need a dynamic import. I dunno why a bunch of people here are talking about `@monaco-editor/react` - thats a different library that uses a CDN.

**Comment by jmarbutt** [comment]
Does anyone know what the actual solution is if you need to import from the `monaco-editor`? It seems to be an issue specifically when you need to import from it

```js
import { languages, type editor } from 'monaco-editor';
```

I think since i need the `languages` and `editor` types it is causing the issue some where in there and i am imagining it would have to be handled in their repo.
