### ISSUE TITLE
i use yarn cd example yarn yarn start !bug i get a erorr

### ISSUE THREAD

**Issue by qq1053831109** [react-monaco-editor/react-monaco-editor#331]
D:\sc\code\react-monaco-editor\example>yarn start
yarn run v1.22.10
$ webpack serve --hot --inline --progress --port 8886
[webpack-cli] Error: Cannot find module 'vs/editor/contrib/rename/onTypeRename'
Require stack:
- D:\sc\code\react-monaco-editor\example\node_modules\monaco-editor-webpack-plugin\out\index.js
- D:\sc\code\react-monaco-editor\example\webpack.config.js
- D:\sc\code\react-monaco-editor\example\node_modules\webpack-cli\lib\webpack-cli.js
- D:\sc\code\react-monaco-editor\example\node_modules\webpack-cli\lib\bootstrap.js
- D:\sc\code\react-monaco-editor\example\node_modules\webpack-cli\bin\cli.js
- D:\sc\code\react-monaco-editor\example\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.resolve (D:\sc\code\react-monaco-editor\example\node_modules\v8-compile-cache\v8-compile-cache.js:164:23)
    at resolveMonacoPath (D:\sc\code\react-monaco-editor\example\node_modules\monaco-editor-webpack-plugin\out\index.js:34:28)
    at D:\sc\code\react-monaco-editor\example\node_modules\monaco-editor-webpack-plugin\out\index.js:181:63
    at Array.map (<anonymous>)
    at createLoaderRules (D:\sc\code\react-monaco-editor\example\node_modules\monaco-editor-webpack-plugin\out\index.js:181:43)
    at MonacoEditorWebpackPlugin.apply (D:\sc\code\react-monaco-editor\example\node_modules\monaco-editor-webpack-plugin\out\index.js:91:23)
    at createCompiler (D:\sc\code\react-monaco-editor\example\node_modules\webpack\lib\webpack.js:69:12)
    at create (D:\sc\code\react-monaco-editor\example\node_modules\webpack\lib\webpack.js:113:15)
    at webpack (D:\sc\code\react-monaco-editor\example\node_modules\webpack\lib\webpack.js:137:31) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\sc\\code\\react-monaco-editor\\example\\node_modules\\monaco-editor-webpack-plugin\\out\\index.js',
    'D:\\sc\\code\\react-monaco-editor\\example\\webpack.config.js',
    'D:\\sc\\code\\react-monaco-editor\\example\\node_modules\\webpack-cli\\lib\\webpack-cli.js',
    'D:\\sc\\code\\react-monaco-editor\\example\\node_modules\\webpack-cli\\lib\\bootstrap.js',
    'D:\\sc\\code\\react-monaco-editor\\example\\node_modules\\webpack-cli\\bin\\cli.js',
    'D:\\sc\\code\\react-monaco-editor\\example\\node_modules\\webpack\\bin\\webpack.js'
  ]
}
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by domoritz** [comment]
It looks like you are using windows. Please use the wsl since We don't support windows.
