### ISSUE TITLE
You may need an additional loader to handle the result of these loaders

### ISSUE THREAD

**Issue by easy868** [react-monaco-editor/react-monaco-editor#615]
```
Uncaught Error: Module parse failed: Unexpected token (41:13)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   }
| 
>   _languageId;
|   _loadingTriggered;
|   _lazyLoadPromise;
    at ./node_modules/monaco-editor/esm/vs/basic-languages/_.contribution.js (storage.js:175:1)
    at __webpack_require__ (bootstrap:790:1)
    at fn (bootstrap:150:1)
    at ./node_modules/monaco-editor/esm/vs/basic-languages/javascript/javascript.contribution.js (javascript.contribution.js:1:1)
    at __webpack_require__ (bootstrap:790:1)
    at fn (bootstrap:150:1)
    at ./include-loader!./node_modules/monaco-editor/esm/vs/editor/editor.api.js (editor.api.js:82:1)
    at __webpack_require__ (bootstrap:790:1)
    at fn (bootstrap:150:1)
    at ./node_modules/react-monaco-editor/lib/index.js (index.ts:1:1)
    at __webpack_require__ (bootstrap:790:1)
    at fn (bootstrap:150:1)
    at ./src/components/ReactMonacoEditor/index.js (index.module.less:13:1)
    at __webpack_require__ (bootstrap:790:1)
    at fn (bootstrap:150:1)
    at ./src/pages/IndexConfig/index.js (index.module.less?0437:45:1)
    at __webpack_require__ (bootstrap:790:1)
    at fn (bootstrap:150:1)
```

**config-overrides.js**

```
const {
  override,
  fixBabelImports,
  addWebpackPlugin,
  addBabelPlugins,
  addLessLoader,
  disableEsLint,
  useBabelRc,
  useEslintRc,
  addWebpackAlias,
  setWebpackPublicPath,
  addWebpackModuleRule,
} = require("customize-cra");
const path = require("path");
const MonacoWebpackPlugin = require("monaco-editor-webpack-plugin");

const APP_DIR = path.resolve(__dirname, "./src");
const MONACO_DIR = path.resolve(__dirname, "./node_modules/monaco-editor");

/* BLOCK INSERT: ModuleImport */

/* BLOCK INSERT: OuterScope */

function resolve(dir) {
  return path.join(__dirname, ".", dir);
}

function deep(config, str) {
  for (var key in config) {
    if (typeof config[key] == "string") {
      config[key] = config[key].replace("static", str);
    } else if (typeof config[key] == "object") {
      deep(config[key], str);
    }
  }
}

const customWebpack = () => config => {
  const appName = "smart-city-metrics";
  if (config.mode == "production") {
    config.output.publicPath = `/${appName}/`;
  } else {
    config.output.publicPath = `./`;
    deep(config, `${appName}`);
  }

  config.output.library = appName;
  config.output.libraryTarget = "umd";
  config.output.jsonpFunction = `webpackJsonp_${appName}`;
  return config;
};

// less.module配置
const getCSSModuleLocalIdent = require("react-dev-utils/getCSSModuleLocalIdent");

const getStyleLoaders = (cssOptions, preProcessor, lessOptions) => {
  const loaders = [
    require.resolve("style-loader"),
    {
      loader: require.resolve("css-loader"),
      options: cssOptions,
    },
    {
      loader: require.resolve("postcss-loader"),
      options: {
        ident: "postcss",
        plugins: () => [
          require("postcss-flexbugs-fixes"),
          require("postcss-preset-env")({
            autoprefixer: {
              flexbox: "no-2009",
            },
            stage: 3,
          }),
        ],
      },
    },
  ];
  if (preProcessor) {
    loaders.push({
      loader: require.resolve(preProcessor),
      options: lessOptions,
    });
  }
  return loaders;
};
// 别名配置
let aliasConfig = {
  "@": resolve("src"),
  /* BLOCK INSERT: AliasResolve */
};

module.exports = {
  webpack: override(
    customWebpack(),
    addWebpackAlias(aliasConfig),
    fixBabelImports("import", {
      libraryName: "antd",
      libraryDirectory: "es",
      style: true,
    }),
    disableEsLint(),
    addLessLoader({
      javascriptEnabled: true,
      modifyVars: {
        "@primary-color": "#4C84FF",
        "@border-radius-base": "4px",
        "@error-color": "#FF5630",
        "@background-color-light": "#F4F5F6",
        "@border-color-split": "#E6EAEF",
        "@btn-primary-bg": "#5392FF",
        "@text-color": "#000001",
        "@text-color-secondary": "#5c6268",
        "@heading-color": "#172b4d",
        "@layout-body-background": "#f1f4fa",
        "@border-color-base": "#d3d9e2",
        "@disabled-color": "fade(#000, 25%)",
        "@disabled-bg": "#f5f5f5",
        "@layout-header-background": "#001529",
        "@switch-bg": "#fff",
      },
      sourceMap: true,
    }),
    addWebpackPlugin(
      new MonacoWebpackPlugin({
        languages: ["javascript"],
      }),
    ),
    addBabelPlugins(["@babel/plugin-proposal-decorators", { legacy: true }]),
    addWebpackModuleRule({
      test: /\.md$/,
      exclude: /(node_modules)/,
      include: APP_DIR,
      use: [
        {
          loader: require.resolve("babel-loader"),
          options: {
            presets: ["@babel/preset-react"],
            plugins: [
              [
                "prismjs",
                {
                  languages: ["javascript", "css", "markup"],
                  plugins: ["line-numbers"],
                  theme: "okaidia",
                  css: true,
                },
              ],
            ],
          },
        },
        {
          loader: "arco-markdown-loader",
        },
      ],
    }),
/*    addWebpackModuleRule({
      test: /\.css$/,
      include: MONACO_DIR,
      use: ["style-loader", "css-loader"],
    }),
    addWebpackModuleRule({
      test: /\.ttf$/,
      use: ["file-loader"],
    }),*/
  /*  addWebpackModuleRule({
        test: /node_modules\/monaco-editor/,
        use: {
            loader: 'babel-loader',
            // if you include your babel config here,
            // you don’t need the `babel.config.json` file
            options: { presets: ['@babel/preset-env'] }
        }
    }),*/
    useBabelRc(),
    config => {
      const oneOf_loc = config.module.rules.findIndex(n => n.oneOf);
      config.module.rules[oneOf_loc].oneOf = [
        {
          test: /\.module\.less$/,
          use: getStyleLoaders(
            {
              importLoaders: 2,
              modules: {
                getLocalIdent: getCSSModuleLocalIdent,
              },
            },
            "less-loader",
          ),
        },
        ...config.module.rules[oneOf_loc].oneOf,
      ];
      return config;
    },
    //useEslintRc("./.eslintrc.json")
  ),
  devServer: function(configFunction) {
    return function(proxy, allowedHost) {
      // Create the default config by calling configFunction with the proxy/allowedHost parameters
      // Default config: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpackDevServer.config.js
      const config = configFunction(proxy, allowedHost);

      // Set loose allow origin header to prevent CORS issues
      config.headers = {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, PATCH, OPTIONS",
        "Access-Control-Allow-Headers": "X-Requested-With, content-type, Authorization",
      };

      return config;
    };
  },
};

```

**Comment by domoritz** [comment]
This repo is for the React wrapper for Monaco. Please file issues about Monaco in the Monaco repo.

**Comment by easy868** [comment]
@domoritz this is Monaco issue，
when i use ```   addWebpackPlugin(
      new MonacoWebpackPlugin({
        languages: ["javascript"]
 })```，This error has occurred
