### ISSUE TITLE
Cannot work with worker-loader together

### ISSUE THREAD

**Issue by jojocys** [react-monaco-editor/react-monaco-editor#673]
**Describe the bug**
react-monaco-editor cannot be used together with worker-loader.

**To Reproduce**
1. create a new typescript app with CRA, run a min react-monaco-editor demo. (everything is fine)

2. install worker loader and add config in config-overrides.js, and start app.

[example repo to reproduce](https://github.com/jojocys/react-monaco-editor-and-worker-loader)

```bash
ERROR in ./node_modules/monaco-editor/esm/vs/editor/editor.worker.js
  Module build failed (from ./node_modules/worker-loader/dist/cjs.js):
  TypeError: Cannot read properties of undefined (reading 'replace')
      at getDefaultChunkFilename (/Users//Documents/test/my-project/node_modules/worker-loader/dist/utils.js:23:24)
      at Object.pitch (/Users//Documents/test/my-project/node_modules/worker-loader/dist/index.js:61:108)

  Child vs/editor/editor compiled with 1 error

  assets by status 1.27 KiB [cached] 1 asset
  ./node_modules/monaco-editor/esm/vs/language/json/json.worker.js 39 bytes [not cacheable] [built] [1 error]
    

  ERROR in ./node_modules/monaco-editor/esm/vs/language/json/json.worker.js
  Module build failed (from ./node_modules/worker-loader/dist/cjs.js):
  TypeError: Cannot read properties of undefined (reading 'replace')
      at getDefaultChunkFilename (/Users//Documents/test/my-project/node_modules/worker-loader/dist/utils.js:23:24)
      at Object.pitch (/Users//Documents/test/my-project/node_modules/worker-loader/dist/index.js:61:108)

  Child vs/language/json/jsonWorker compiled with 1 error
```

details of my config-overrides.js
```js
const webpack = require('webpack');
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');

module.exports = function override(config, env) {
    config.plugins.push(
        new MonacoWebpackPlugin({
            languages: ['json']
        })
    );
    config.stats = {
        children: true
    }
    config.module.rules.push(
        {
            test: /\.worker\.js$/,
            use: {
                loader: 'worker-loader',
                options: {
                    inline: 'fallback',
                    filename: '[contenthash].worker.js',
                },
            },
        },
        {
            test: /\.worker\.ts$/,
            use: [
                {
                    loader: 'worker-loader',
                    options: {
                        inline: 'fallback',
                        filename: '[contenthash].worker.js',
                    },
                },
                'ts-loader',
            ],
        },
    );
    return config;
};

```

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Bundler webpack5 (CRA)

- [ ] I will try to send a pull request to fix this issue.

**Comment by jojocys** [comment]
sorry, it is not an issues of [react-monaco-editor](https://github.com/react-monaco-editor/react-monaco-editor) so I just closed it.

I think it is problem of monaco plugin and worker loader. I change the worker loader's regexp to match workers in my source code only and solved it temporarily
