### ISSUE TITLE
Error: Window is not defined

### ISSUE THREAD

**Issue by Anchel123** [react-monaco-editor/react-monaco-editor#944]
i'm getting on build the error window is not defined

Error: 

```
⨯ node_modules/monaco-editor/esm/vs/base/browser/window.js (14:26) @ window
 ⨯ ReferenceError: window is not defined
    at __webpack_require__ (/home/anchel/Desktop/falkordb/falkordb-browser/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/home/anchel/Desktop/falkordb/falkordb-browser/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/home/anchel/Desktop/falkordb/falkordb-browser/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/home/anchel/Desktop/falkordb/falkordb-browser/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/home/anchel/Desktop/falkordb/falkordb-browser/.next/server/webpack-runtime.js:33:43)
    at eval (./app/graph/GraphView.tsx:13:71)
    at (ssr)/./app/graph/GraphView.tsx (/home/anchel/Desktop/falkordb/falkordb-browser/.next/server/app/graph/page.js:316:1)
    at __webpack_require__ (/home/anchel/Desktop/falkordb/falkordb-browser/.next/server/webpack-runtime.js:33:43)
    at eval (./app/graph/page.tsx:10:68)
    at (ssr)/./app/graph/page.tsx (/home/anchel/Desktop/falkordb/falkordb-browser/.next/server/app/graph/page.js:349:1)
    at __webpack_require__ (/home/anchel/Desktop/falkordb/falkordb-browser/.next/server/webpack-runtime.js:33:43)
    at JSON.parse (<anonymous>)
null
```

my code:

```ts
import Editor, { Monaco } from "@monaco-editor/react";
import * as monaco from "monaco-editor";

const EditorComponent = () => {

const handleEditorWillMount = (monacoInstance: Monaco) => {
        monacoInstance.editor.defineTheme('custom-theme', {
            base: 'vs-dark',
            inherit: false,
            rules: [
                { token: 'keyword', foreground: '#99E4E5' },
                { token: 'type', foreground: '#89D86D' },
            ],
            colors: {
                'editor.background': '#1F1F3D',
                'editor.foreground': 'ffffff',
            },
        });
    };

    const handleEditorDidMount = (e: monaco.editor.IStandaloneCodeEditor) => {
        editorRef.current = e
        e.addAction({
            id: 'handle-enter-press',
            label: 'Handle Enter Press',
            // eslint-disable-next-line no-bitwise
            keybindings: [monaco.KeyMod.CtrlCmd | monaco.KeyCode.Enter],
            precondition: "!suggestWidgetVisible",
            contextMenuGroupId: 'navigation',
            contextMenuOrder: 1.5,
            run: async () => {
                submitQuery.current?.click()
            }
        });
    }
return (
 <Editor
                                className="Editor"
                                language="cypher"
                                options={monacoOptions}
                                value={query}
                                onChange={(val) => setQuery(val || "")}
                                theme="custom-theme"
                                beforeMount={handleEditorWillMount}
                                onMount={handleEditorDidMount}
                            />
)
}

export default EditorCompnonet
```

**Environment (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Bundler: nextjs

**Comment by adippel** [comment]
I am seeing the same on nextjs 14.2.5, macOS and Chrome using @monaco-editor/react 4.6.0

**Comment by CamdenSpehl** [comment]
I have the exact same issue, did you find a fix?

**Comment by jmaldon1** [comment]
Its because of `import * as monaco from "monaco-editor";` or `import * as monaco from "monaco-editor/esm/vs/editor/editor.api";` which seems to be required for type definitions. Not sure how to fix this though

**Comment by foobarfighter** [comment]
I'm seeing this issue too.  Is there a workaround?

**Comment by mazoqui** [comment]
I managed to get rid of the error by adding the "use client" statement in all files that included the monaco lib
